### ISSUE TITLE
Using card 4000000000003220 doesn't trigger 3d secure modal after page refreshing.

### ISSUE THREAD

**Issue by vvitto** [stripe/react-stripe-elements#405]
![Снимок экрана 2019-08-12 в 17 32 07](https://user-images.githubusercontent.com/26697512/62872967-30b42f80-bd27-11e9-81d2-021f6b1f12d7.png)

I have weird behaviors using card with 3d secure 2 . When i invoke handleCardAction, not clicking any buttons in the modal, then do page refresh and invoke handleCardAction again, it doesn't show me any modal window with 3d secure again. It works properly with other kinds of cards.

I mentioned that these two cases have different next_actions object structures in returned paymentIntent.

1 Case with reloading: 
```
"next_action": {
    "type": "use_stripe_sdk",
    "use_stripe_sdk": {
      "type": "stripe_3ds2_challenge",
      "stripe_js": {
        "three_d_secure_2_source": "...",
        "directory_server_name": "visa",
        "server_transaction_id": "...",
        "acs_transaction_id": "...",
        "acs_url": "https://hooks.stripe.com/3d_secure_2_test/challenge",
        "three_ds_optimizations": ""
      }
    }
  },```

2 Case without reloading: 
```"next_action": {
    "type": "use_stripe_sdk",
    "use_stripe_sdk": {
      "type": "stripe_3ds2_fingerprint",
      "three_d_secure_2_source": "...",
      "directory_server_name": "visa",
      "server_transaction_id": "...",
      "three_ds_method_url": "",
      "three_ds_optimizations": "",
      "directory_server_encryption": {
        "directory_server_id": "...",
        "algorithm": "RSA",
        "certificate": "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\n",
        "root_certificate_authorities": [
          "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\n"
        ]
      }
    }
  },```

**Comment by asolove-stripe** [comment]
Hi @vvitto: thanks for filing, we definitely understand this is a painful problem. We are working on a fix. Note that this problem only occurs in testmode, so live payments aren't having this problem!

**Comment by CarlosTrapet** [comment]
I've had this scenario too, where the structure of next_action changes (apparently randomly) like @vvitto mentioned. Not sure if this is intended behaviour, but I fail to see what would be the trigger for the different responses.

**Comment by dweedon-stripe** [comment]
Hi @CarlosTrapet @vvitto,

We just rolled out a fix for this bug.

@CarlosTrapet: This is the intended behavior, but you should not base any business logic off of what is in the `use_stripe_sdk` hash. This is considered private data and we make no guarantees that it we won't change its shape.

**Comment by DaniSido** [comment]
Hi, any updates?

**Comment by dweedon-stripe** [comment]
Hi @DaniSido are you seeing this today? This was fixed months ago.

**Comment by Nek-** [comment]
What is actually fixed ? I also just saw it. Still only in test mode?

**Comment by naliva** [comment]
the issue remains in live mode. (no popup for 3ds authentication after calling handleCardAction()). 
`
    "use_stripe_sdk": {
      "type": "stripe_3ds2_fingerprint",
`
this was payment intend param when no-popup. the payment itself has been marked as 3dsecure authorised.

**Comment by robz-stripe** [comment]
Reopening this since we have a couple of reports of it still occurring.

**Comment by IamSonOfTenny** [comment]
Can confirm i'm getting the same issue however it is present in the response JSON, just not mapping correctly to the response model (PaymentIntent)
![image](https://user-images.githubusercontent.com/30115849/107392013-29730b00-6af1-11eb-88f8-c6f0246215ee.png)
![image](https://user-images.githubusercontent.com/30115849/107392625-c9c92f80-6af1-11eb-8f66-0be8ec6c510b.png)

**Comment by dweedon-stripe** [comment]
> the issue remains in live mode. (no popup for 3ds authentication after calling handleCardAction()).
> `"use_stripe_sdk": { "type": "stripe_3ds2_fingerprint",`
> this was payment intend param when no-popup. the payment itself has been marked as 3dsecure authorised.

@naliva this is expected to happen sometimes in livemode. Sometimes the bank approves the payment after the "fingerprint" step without requiring us to present a 3DS challenge. This is why the payment is marked as 3dsecure authorized.

@Nek- did you see this happen in testmode?

**Comment by sashko-stripe** [comment]
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.
